config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :vacations
  get 'home/index'
  get 'home/about'
  get 'vacations/new'
  get 'vacations/index'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/vacation.rb
class Vacation < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/vacations_controller.rb
class VacationsController < ApplicationController
  before_action :set_vacation, only: %i[ show edit update destroy ]

  # GET /vacations or /vacations.json
  def index
    @vacations = Vacation.all
  end

  # GET /vacations/1 or /vacations/1.json
  def show
  end

  # GET /vacations/new
  def new
    @vacation = Vacation.new
  end

  # GET /vacations/1/edit
  def edit
    validate(@vacation)
  end

  # POST /vacations or /vacations.json
  def create
    @vacation = Vacation.new(vacation_params)
    
    validate(@vacation)

    respond_to do |format|
      if @vacation.save
        format.html { redirect_to vacation_url(@vacation), notice: "Vacation was successfully created." }
        format.json { render :show, status: :created, location: @vacation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vacation.errors, status: :unprocessable_entity }
      end
    end
  end

  def validate(vacation)
    # puts vacation.first_name
    # puts vacation.last_name
    # puts vacation.email
    # puts vacation.vacation_days
    # puts vacation.starting_date
    # puts vacation.ending_date
    # puts vacation.bonus

    #calcula o end_date dia baseado no start_date e vacation_days
    vacation_days = vacation.vacation_days-1
    end_date = (vacation.starting_date+vacation_days).to_s
    vacation.ending_date = end_date
  end

  # PATCH/PUT /vacations/1 or /vacations/1.json
  def update

    respond_to do |format|
      if @vacation.update(vacation_params)
        format.html { redirect_to vacation_url(@vacation), notice: "Vacation was successfully updated." }
        format.json { render :show, status: :ok, location: @vacation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vacation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vacations/1 or /vacations/1.json
  def destroy
    @vacation.destroy!

    respond_to do |format|
      format.html { redirect_to vacations_url, notice: "Vacation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vacation
      @vacation = Vacation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vacation_params
      params.require(:vacation).permit(:first_name, :last_name, :email, :vacation_days, :starting_date, :ending_date, :bonus)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/vacations_helper.rb
module VacationsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    <%= link_to "Vacations App", root_path, class:"navbar-brand"%>
    <%# <a class="navbar-brand" href="#">Navbar</a> %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%= link_to "Vacations", vacations_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "About", home_about_path, class:"nav-link" %>
          <%# <a class="nav-link" href="#">Link</a> %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, data: { turbo_method: :delete }, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
          </li>
        <%else%>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
          </li>
        <%end%>
      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About</h1>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vacation</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>

  <body>
    <div>
      <%= render 'home/header' %>
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

app/views/vacations/_form.html.erb
<div class="p-1 m-1 rounded-3" style="background-color: lightblue">
  <div class="container-fluid">
    <%= form_with(model: vacation) do |form| %>
      <% if vacation.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(vacation.errors.count, "error") %> prohibited this vacation from being saved:</h2>

        <ul>
          <% vacation.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group input-group" style="display: flex; justify-content: space-between" >
      <%= form.text_field :first_name, class: "form-control", id: "autoSizingInput", placeholder: "First name"  %>
      <%= form.text_field :last_name, class: "form-control", id: "autoSizingInput", placeholder: "Last name"  %>
    </div> 

    <%= form.text_field :email, class: "form-control ", id: "autoSizingInput", placeholder: "example@email.com"  %>
    <div class="input-group">
      <div class="input-group-text">Days</div>
      <%= form.number_field :vacation_days, class: "form-control", id: "autoSizingInputGroup", placeholder: "5-30" %>
    </div>

    <div class="form-group">
      <div class="input-group">
        <div class="input-group-text">Starting Date</div>
         <%= form.date_field :starting_date, class: "form-control"  %>
      </div> 
      <%# <%= form.label :ending_date, style: "display: block" %>
      <%# <%= form.date_field :ending_date %>
    </div>
   
    <div class="form-group" style="display: flex">
       Bonus:  <%= form.check_box :bonus %>
    </div>

    <div class="form-group">
      <%= form.submit class: 'btn btn-secondary btn-sm', value: "Save" %>
    </div>
    <% end %>
  </div>
</div>

app/views/vacations/_show.html.erb
<%= form_with(model: vacation) do |form| %>
  <% if vacation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(vacation.errors.count, "error") %> prohibited this vacation from being saved:</h2>

      <ul>
        <% vacation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
      <tr>
        <td><%= vacation.first_name %></td>
        <td><%= vacation.last_name %></td>
        <td><%= vacation.email %></td>
        <td><%= vacation.vacation_days %></td>
        <td><%= vacation.starting_date %></td>
        <td><%= vacation.ending_date %></td>
        <%
          puts vacation.bonus
          if vacation.bonus == "1"
            vacation.bonus = "Y"
          else
            vacation.bonus = "N"
          end
        %>
        <td><%= vacation.bonus.to_s%></td>
        <td><%= link_to "Edit", edit_vacation_path(vacation), class:"btn btn-secondary btn-sm" %></td>
        <%# <td><%= link_to "X", destroy_vacation_path(vacation)</td>  %>
      </tr>
<% end %>

app/views/vacations/_vacation.html.erb
<div id="<%= dom_id vacation %>">
  <p>
    <strong>First name:</strong>
    <%= vacation.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= vacation.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= vacation.email %>
  </p>

  <p>
    <strong>Vacation days:</strong>
    <%= vacation.vacation_days %>
  </p>

  <p>
    <strong>Starting date:</strong>
    <%= vacation.starting_date %>
  </p>

  <p>
    <strong>Ending date:</strong>
    <%= vacation.ending_date %>
  </p>

  <%# <p>
    <strong>Bonus:</strong>
    <%= vacation.bonus %>
  <%# </p> %>

</div>

app/views/vacations/edit.html.erb
<h1>Editing vacation</h1>
<div class="container">
  <%= render "form", vacation: @vacation %>
  <div>
    <br>
    <%= link_to "Back", vacations_path, class:"btn btn-secondary btn-sm" %>
  </div>
</div>

app/views/vacations/index.html.erb
<h1>Vacations List (INDEX)</h1>
<div id="vacations" class="container">
  <table class="table table-hover table-striped table-bordered">
      <thead>
        <tr class="table-dark ">
          <th scope="col">First name</th>
          <th scope="col">Last name</th>
          <th scope="col">Email</th>
          <th scope="col">Vacation days</th>
          <th scope="col">Starting date</th>
          <th scope="col">Ending date</th>
          <th scope="col">Bonus?</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
      <% @vacations.each do |vacation| %>
        <%= render "show", vacation: vacation %>
      <% end %>
      </tbody>
  </table>
  <%= link_to "New vacation", new_vacation_path,class:"btn btn-secondary btn-sm" %>
</div>

app/views/vacations/new.html.erb
<h1>Add new vacation</h1>
<div class="container">
  <div>
    <%= render "form", vacation: @vacation %>
    <%= link_to "Back", vacations_path, class:"btn btn-secondary btn-sm" %>
  </div>
</div>

app/views/vacations/show.html.erb
<div class="p-1 m-1 rounded-3 ">
  <div class="container-fluid container">

    <h1 class="fw-bold"><%= @vacation.first_name + " " + @vacation.last_name%></h1>
    <div class="p-2">
      <p class="col-md-8"><span class="fw-bold">Email:</span> <%= @vacation.email %></p>
      <p class="col-md-8"><span class="fw-bold">Days:</span> <%= @vacation.vacation_days %> </p>
      <p class="col-md-8"><span class="fw-bold">Starting:</span> <%= @vacation.starting_date %> </p>
      <p class="col-md-8"><span class="fw-bold">Ending:</span> <%= @vacation.ending_date %> </p>
    </div>
    <%= link_to "Back", vacations_path, class:"btn btn-secondary btn-sm" %>
  </div>
</div>